version: '3' # vs mais atual
    # dotnet run --urls=http://0.0.0.0:8080/
    # "dotnet", "SistemaPedidos.dll", "--server.urls", "https://+:5000"
    # dotnet SistemaPedidos.dll --server.urls https://+:8080
    # dotnet watch run --server.urls http://0.0.0.0:8080


    # curl http://localhost:8080
    # Criar migration
    # dotnet ef migrations add SistemaPedidos
    # Executar migration
    # dotnet ef database update
    # dotnet run seeddata

# Requisitos obrigatórios:
# • O projeto deverá ter no mínimo essas três entidades: Fornecedor, Produto, Pedidos;
# • A entidade Fornecedor deverá ter no mínimo 5 propriedades: Razão Social, CNPJ, UF, Email Contato e
# Nome Contato;
# • A entidade Produto deverá ter no mínimo 4 propriedades: Código, Descrição, Data do
# Cadastro, Valor do Produto;
# • A entidade Pedido deverá ter no mínimo 6 propriedades: Código do pedido, Data do pedido,
# Produto, Quantidade de Produtos, Fornecedor, Valor Total do Pedido;
# • CRUD de Fornecedor, Produto, Pedidos;
# • Listagem dos pedidos por Fornecedor mostrando o valor total do pedido;

services: 

  # SistemasPedidos
  api:
    build: .
    container_name: sistema-pedidos
    restart: always
    tty: true
    volumes:      
      - ./app:/app
      - ./front:/front
    ports:
      - "8080:8080"
      - "3000:3000"